site_name: ${{ values.name }}
site_description: ${{ values.description }}

nav:
  - Home: index.md
  - Deployment: deployment.md
  - API Reference: api.md

plugins:
  - techdocs-core

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
